services:
  # Web service
  - type: web
    name: emailengine
    env: node
    repo: https://github.com/postalsys/emailengine.git
    buildCommand: npm install --production
    startCommand: npm start
    envVars:
      - key: EENGINE_REDIS
        fromService:
          type: redis
          name: ee-redis
          property: connectionString
      - key: EENGINE_SECRET
        generateValue: true
    autoDeploy: false # optional

  # The Redis instance
  - type: redis
    name: ee-redis
    ipAllowList: []
    maxmemoryPolicy: noeviction # optional (defaults to allkeys-lru)
